# Main options
CONFIG_SERIAL=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y

# I2C enable
CONFIG_I2C=y

# UART enable
CONFIG_UART_CONSOLE=y
CONFIG_UART_CONSOLE_ON_DEV_NAME="UART_0"

# GPIO - buttons and LED
CONFIG_GPIO=y

# PWM enable
CONFIG_PWM=y

# Kernel enable (mutex, semaphors, threads)
CONFIG_KERNEL=y